feat: add `CacheReader` for SStable
tonbo-io/tonbo pull request #193
Opened 2024-10-23 03:34 UTC by KKould

2024-11-11 09:00 UTC, ethe requested changes

2024-11-11 09:00 UTC, ethe commented on Cargo.toml
> +fusio = { git = "https://github.com/tonbo-io/fusio.git", rev = "db305599ae88c7a934ab1ab235d8b3efda95a242", package = "fusio", version = "0.3.1", features = [
0.3.3 is released, I think the source rev could be removed

2024-11-11 09:00 UTC, ethe commented on Cargo.toml
> +msrv = "1.81.0"
Are there any possible way to keep msrv?

2024-11-11 09:00 UTC, ethe commented on tonbo_ext_reader/src/lib.rs
> +        cache_path: impl AsRef<std::path::Path> + Send,
remove `cache_` prefix, all of us know that arguments are used to build cache.

2024-11-11 09:00 UTC, ethe commented on tonbo_ext_reader/src/lib.rs
> +        cache_meta_capacity: usize,
It should be better to use [Builder pattern](https://rust-unofficial.github.io/patterns/patterns/creational/builder.html) here, `pub trait CacheReader: From<CacheReaderBuilder>` should be fine

2024-11-11 09:00 UTC, ethe commented on tonbo_ext_reader/Cargo.toml
> +tokio = { version = "1", features = ["full"] }
Add a new line here

2024-11-11 09:00 UTC, ethe commented on tonbo_ext_reader/Cargo.toml
> +fusio = { git = "https://github.com/tonbo-io/fusio.git", rev = "db305599ae88c7a934ab1ab235d8b3efda95a242", package = "fusio", version = "0.3.1", features = [
Remove the source rev here

2024-11-11 09:00 UTC, ethe commented on tonbo_ext_reader/Cargo.toml
> +foyer = { version = "0.12" }
Could foyer be a optional feature?

2024-11-11 09:00 UTC, ethe commented on tonbo_ext_reader/Cargo.toml
> +anyhow = "1"
It should better to use `Box<dyn std::error::Error + Send + Sync>`, I can not see the necessary for `anyhow` integration.

2024-11-11 09:00 UTC, ethe commented on bindings/python/src/db.rs
> +use tonbo_ext_reader::foyer_reader::FoyerReader;
It should use Tonbo's cache reader here, Python binding must not relies on Tokio

2024-11-11 09:00 UTC, ethe commented on rust-toolchain.toml
> +channel = "1.81.0"
"1.82"

2024-11-11 09:00 UTC, ethe commented on src/version/set.rs
> +            path_to_local(&option.cache_path).unwrap(),
Are there any validations to ensure `cache_path` is valid to unwrap?

2024-11-11 10:24 UTC, KKould commented on Cargo.toml
> +msrv = "1.81.0"
foyer requires 1.81.0 and above :eyes:

2024-11-11 10:54 UTC, KKould commented on tonbo_ext_reader/Cargo.toml
> +anyhow = "1"
I tried it, but when using foyer's error in box, the compiler will prompt that anyhow is required.

2024-11-11 11:20 UTC, KKould commented on src/version/set.rs
> +            path_to_local(&option.cache_path).unwrap(),
the `cache_path` is obtained by joining `base_path`. Base_path should be local, but after I checked just now, `base_path` does not seem to guarantee that it is local.

2024-11-11 11:30 UTC, KKould commented on .github/workflows/ci.yml
For testing, need to be restored before merging

2024-11-12 02:57 UTC, ethe commented on tonbo_ext_reader/Cargo.toml
> +anyhow = "1"
convert `anyhow::Error` to `Box<dyn std::error::Error + Send + Sync>` is definitely possible

2025-05-12 07:06 UTC, closed without merging